-- MySQL Script generated by MySQL Workbench
-- 04/26/15 20:13:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blogmedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blogmedb` ;

-- -----------------------------------------------------
-- Schema blogmedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogmedb` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `blogmedb` ;

-- -----------------------------------------------------
-- Table `blogmedb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogmedb`.`Users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(150) NOT NULL,
  `Password` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `FullName` VARCHAR(150) NULL,
  `Email` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogmedb`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogmedb`.`Posts` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(150) NOT NULL,
  `Content` VARCHAR(1000) NOT NULL,
  `Visits` INT NULL,
  `User_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Posts_Users_idx` (`User_Id` ASC),
  CONSTRAINT `fk_Posts_Users`
    FOREIGN KEY (`User_Id`)
    REFERENCES `blogmedb`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogmedb`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogmedb`.`Comments` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CommenterName` VARCHAR(150) NOT NULL,
  `CommenterEmail` VARCHAR(150) NULL,
  `Content` VARCHAR(500) NOT NULL,
  `Post_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Comments_Posts_idx` (`Post_Id` ASC),
  CONSTRAINT `fk_Comments_Posts`
    FOREIGN KEY (`Post_Id`)
    REFERENCES `blogmedb`.`Posts` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogmedb`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogmedb`.`Tags` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogmedb`.`Posts_has_Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogmedb`.`Posts_has_Tags` (
  `Post_Id` INT NOT NULL,
  `Tag_Id` INT NOT NULL,
  PRIMARY KEY (`Post_Id`, `Tag_Id`),
  INDEX `fk_Posts_has_Tags_Tags_idx` (`Tag_Id` ASC),
  INDEX `fk_Posts_has_Tags_Posts_idx` (`Post_Id` ASC),
  CONSTRAINT `fk_Posts_has_Tags_Posts`
    FOREIGN KEY (`Post_Id`)
    REFERENCES `blogmedb`.`Posts` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posts_has_Tags_Tags`
    FOREIGN KEY (`Tag_Id`)
    REFERENCES `blogmedb`.`Tags` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
