-- MySQL Script generated by MySQL Workbench
-- 02/12/15 14:58:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema University_Database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema University_Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `University_Database` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `University_Database` ;

-- -----------------------------------------------------
-- Table `University_Database`.`Faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University_Database`.`Faculties` (
  `idFaculty` INT NOT NULL AUTO_INCREMENT,
  `nameFaculty` VARCHAR(45) NOT NULL,
  `DepartmentId` INT NULL,
  PRIMARY KEY (`idFaculty`),
  UNIQUE INDEX `idFaculties_UNIQUE` (`idFaculty` ASC),
  UNIQUE INDEX `nameFaculty_UNIQUE` (`nameFaculty` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University_Database`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University_Database`.`Departments` (
  `idDepartment` INT NOT NULL AUTO_INCREMENT,
  `nameDepartment` VARCHAR(45) NOT NULL,
  `ProfessorId` INT NULL,
  `CourseId` INT NULL,
  `Faculties_idFaculty` INT NOT NULL,
  PRIMARY KEY (`idDepartment`),
  UNIQUE INDEX `idDepartment_UNIQUE` (`idDepartment` ASC),
  INDEX `fk_Departments_Faculties_idx` (`Faculties_idFaculty` ASC),
  CONSTRAINT `fk_Departments_Faculties`
    FOREIGN KEY (`Faculties_idFaculty`)
    REFERENCES `University_Database`.`Faculties` (`idFaculty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University_Database`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University_Database`.`Professors` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `titleId` INT NULL,
  `CourseId` INT NULL,
  `Departments_idDepartment` INT NOT NULL,
  PRIMARY KEY (`idProfessor`),
  UNIQUE INDEX `idProfessor_UNIQUE` (`idProfessor` ASC),
  UNIQUE INDEX `nameProfessor_UNIQUE` (`name` ASC),
  INDEX `fk_Professors_Departments1_idx` (`Departments_idDepartment` ASC),
  CONSTRAINT `fk_Professors_Departments1`
    FOREIGN KEY (`Departments_idDepartment`)
    REFERENCES `University_Database`.`Departments` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University_Database`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University_Database`.`Courses` (
  `idCourses` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `studentId` INT NULL,
  `Departments_idDepartment` INT NOT NULL,
  `Professors_idProfessor` INT NOT NULL,
  PRIMARY KEY (`idCourses`),
  UNIQUE INDEX `idCourses_UNIQUE` (`idCourses` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_Courses_Departments1_idx` (`Departments_idDepartment` ASC),
  INDEX `fk_Courses_Professors1_idx` (`Professors_idProfessor` ASC),
  CONSTRAINT `fk_Courses_Departments1`
    FOREIGN KEY (`Departments_idDepartment`)
    REFERENCES `University_Database`.`Departments` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_Professors1`
    FOREIGN KEY (`Professors_idProfessor`)
    REFERENCES `University_Database`.`Professors` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University_Database`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University_Database`.`Students` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `DepartmentId` INT NULL,
  `CourseId` INT NULL,
  `Faculties_idFaculty` INT NOT NULL,
  PRIMARY KEY (`idStudent`),
  UNIQUE INDEX `idStudents_UNIQUE` (`idStudent` ASC),
  INDEX `fk_Students_Faculties1_idx` (`Faculties_idFaculty` ASC),
  CONSTRAINT `fk_Students_Faculties1`
    FOREIGN KEY (`Faculties_idFaculty`)
    REFERENCES `University_Database`.`Faculties` (`idFaculty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University_Database`.`Titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University_Database`.`Titles` (
  `idTitles` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Professors_idProfessor` INT NOT NULL,
  PRIMARY KEY (`idTitles`),
  UNIQUE INDEX `idTitles_UNIQUE` (`idTitles` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_Titles_Professors1_idx` (`Professors_idProfessor` ASC),
  CONSTRAINT `fk_Titles_Professors1`
    FOREIGN KEY (`Professors_idProfessor`)
    REFERENCES `University_Database`.`Professors` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University_Database`.`Courses_has_Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University_Database`.`Courses_has_Students` (
  `Courses_idCourses` INT NOT NULL,
  `Students_idStudent` INT NOT NULL,
  INDEX `fk_Courses_has_Students_Students1_idx` (`Students_idStudent` ASC),
  INDEX `fk_Courses_has_Students_Courses1_idx` (`Courses_idCourses` ASC),
  CONSTRAINT `fk_Courses_has_Students_Courses1`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `University_Database`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_Students_Students1`
    FOREIGN KEY (`Students_idStudent`)
    REFERENCES `University_Database`.`Students` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
